name: gcp-prod

on:
  workflow_run:
    workflows: ["gcp-test"]
    types: [completed]
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: infra
    env:
      REGION: europe-west1
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      ENVIRONMENT: prod
      TF_VAR_environment: prod
      TF_VAR_project_level_environment: prod
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
      TF_VAR_create_default_firestore_database: 'false'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build cloud function sources and Dendrite static site
        working-directory: ./
        run: |
          npm ci
          npm run build:dendritestories-co-nz
          npm run build:cloud

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          install_components: alpha

      - name: Log Google Cloud authentication details
        run: |
          gcloud auth list
          gcloud config list account
          gcloud config get-value project

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Cache Terraform plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: tf-plugins-${{ runner.os }}-${{ hashFiles('infra/**/.terraform.lock.hcl') }}

      - name: Terraform environment configuration
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir = "~/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init (Validate)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Terraform Plan
        run: terraform plan -lock-timeout=5m -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -lock-timeout=5m -auto-approve tfplan
